apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ci-cd-demo
  labels:
    app: java-ci-cd-demo
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: java-ci-cd-demo
  template:
    metadata:
      labels:
        app: java-ci-cd-demo
    spec:
      containers:
        - name: java-ci-cd-demo
          image: mzamankhan1/java-ci-cd-demo:latest  # Use your Docker Hub image
          ports:
            - containerPort: 8080  # Application port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"  # Set environment variables if needed
---
apiVersion: v1
kind: Service
metadata:
  name: java-ci-cd-demo-service
spec:
  selector:
    app: java-ci-cd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Match the container port
  type: LoadBalancer  # Change to NodePort if using a local cluster
